meta_product_name: "CarClique"
meta_title: "CarClique - Buy your dream car"
meta_description: "A car marketplace with a twist, we have a unique bidding system that allows you to pay what you really want!"
meta_image: "Bugatti.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
